# Generated by Django 6.1 on 2026-09-01 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse_complete', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('horaires_ouverture', models.CharField(blank=True, max_length=255, null=True)),
                ('url_image', models.ImageField(blank=True, null=True, upload_to='points_vente/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('editeur', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('poids', models.FloatField(blank=True, help_text='Poids en kg', null=True)),
                ('type_produit', models.CharField(choices=[('livre', 'Livre'), ('bible', 'Bible'), ('cd', 'CD'), ('cadeau', 'Cadeau/Papeterie')], default='livre', max_length=20)),
                ('est_edition_cedi', models.BooleanField(default=False)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=3)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie_article', models.CharField(choices=[('enseignement', 'Enseignement BM'), ('verite_fondamentale', 'Vérité fondamentale BM'), ('conseil', 'Conseil spirituel'), ('partage', 'Partage de lecture')], max_length=30)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcedi.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('attente_paiement', 'En attente de paiement'), ('payee', 'Payée'), ('en_preparation', 'En préparation'), ('prete_retrait', 'Prête pour retrait'), ('expediee', 'Expédiée'), ('livree', 'Livrée')], default='attente_paiement', max_length=20)),
                ('mode_livraison', models.CharField(choices=[('retrait', 'Retrait en point de vente'), ('livraison', 'Livraison à domicile')], max_length=20)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('frais_port', models.IntegerField(default=0)),
                ('montant_total', models.IntegerField()),
                ('reference_commande', models.CharField(max_length=50, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('point_vente_retrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcedi.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire_au_moment', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='appcedi.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcedi.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(upload_to='produits/')),
                ('est_principale', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appcedi.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcedi.categorie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcedi.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(through='appcedi.ProduitCategorie', to='appcedi.categorie'),
        ),
        migrations.CreateModel(
            name='ProduitPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcedi.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_reduction', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('fixe', 'Montant fixe')], max_length=20)),
                ('valeur_reduction', models.FloatField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('est_vente_flash', models.BooleanField(default=False)),
                ('produits', models.ManyToManyField(through='appcedi.ProduitPromotion', to='appcedi.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produitpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcedi.promotion'),
        ),
        migrations.CreateModel(
            name='QuestionConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_question', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_question', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('repondu', 'Répondu')], default='en_attente', max_length=20)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='appcedi.produit')),
            ],
            options={
                'unique_together': {('produit', 'utilisateur')},
            },
        ),
    ]
