# Generated by Django 6.1 on 2026-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcedi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='categorie_article',
            field=models.CharField(choices=[('enseignement', 'Enseignement BM'), ('verite_fondamentale', 'Vérité fondamentale'), ('conseil', 'Conseil spirituel'), ('partage', 'Partage de lecture')], max_length=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(choices=[('livre', 'Livre'), ('bible', 'Bible'), ('cd', 'CD'), ('cadeau', 'Cadeau')], default='livre', max_length=20),
        ),
    ]
