# Generated by Django 6.1 on 2026-09-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcedi', '0002_alter_articleblog_categorie_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(blank=True, through='appcedi.ProduitCategorie', to='appcedi.categorie'),
        ),
    ]
