# Generated by Django 6.1 on 2026-09-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcedi', '0003_alter_produit_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
