# Generated by Django 6.1 on 2026-09-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcedi', '0004_articleblog_image_principale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblog',
            name='image_principale',
        ),
    ]
