# Generated by Django 6.0.1 on 2026-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcedi', '0005_remove_articleblog_image_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
